#!/usr/bin/env bash
# Fizzbuzz
index=1
while ((index <= 100))
do
  if ((index % 15 == 0))
  then
    echo "FizzBuzz"
  elif ((index % 3 == 0))
  then
    echo "Fizz"
  elif ((index % 5 == 0))
  then
    echo "Buzz"
  else
    echo $index
  fi
  index=$((index + 1))
done
